[package]
name = "javadoc-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
reqwest = {version = "0.11", features = ["blocking"]}
scraper = "0.12.0"
